### PR TITLE
Refactor focus.nvim

### PR DESCRIPTION
**Pull request by cryptomilk**
This is work in progress. It actually removes all filetype and buftype settings. The reason is that the user should handle it and add autcmds to his config to do what he wants. focus should not add more and more quirks for plugins.

The other thing is that it doesn't have test, so I've started to write tests with mini.test.

```
make test
nvim --version | head -n 1 && echo ''
NVIM v0.8.3

nvim --headless --noplugin -u ./tests/minimal_init.lua \
        -c "lua require('mini.test').setup()" \
        -c "lua MiniTest.run({ execute = { reporter = MiniTest.gen_reporter.stdout({ group_depth = 1 }) } })"
Total number of cases: 2
Total number of groups: 1

tests/test_setup.lua: oo

Fails (0) and Notes (0)
```

### CODE REVIEW

**Comment by beauwilliams** [comment]
Had a quick look over so far but looking great! I will take some time over weekend to review over and test it out 👍

**Comment by cryptomilk** [comment]
Note that it's the user responsibility to disable focus if he doesn't want it. Here is an example:

```lua
    -- Disable focus
    local ignore_filetypes = { 'neo-tree' }
    local ignore_buftypes = { 'nofile', 'prompt', 'popup' }

    local augroup =
        vim.api.nvim_create_augroup('FocusDisable', { clear = true })

    vim.api.nvim_create_autocmd('WinEnter', {
        group = augroup,
        callback = function(_)
            if vim.tbl_contains(ignore_buftypes, vim.bo.buftype) then
                vim.b.focus_disable = true
            end
        end,
        desc = 'Disable focus autoresize for BufType',
    })

    vim.api.nvim_create_autocmd('FileType', {
        group = augroup,
        callback = function(_)
            if vim.tbl_contains(ignore_filetypes, vim.bo.filetype) then
                vim.b.focus_disable = true
            end
        end,
        desc = 'Disable focus autoresize for FileType',
    })
```

**Comment by cryptomilk** [comment]
Btw. the project doesn't have a LICENSE!

**Comment by beauwilliams** [comment]
I have added MIT license think that should do, what do you think? 👍

**Comment by beauwilliams** [comment]
I have also added justfile back I use that to store commands for the project, or do you think we should use something else? I use justfile across most projects these days

**Comment by beauwilliams** [comment]
I had success getting the refactor up and running, tests running. 

I also wrote some autocmds that work with my setup. I like this approach it allows you do define more custom ones and extend them instead of baking into plugin.

We can provide lots of readme examples as needs & crowd sourced as people post their ones.

For me, with telescope and nvimtree I have success with below, had to use BufEnter

```
local ignore_treetypes = { 'neo-tree', 'Nvimtree', 'nerdtree', 'chadtree', 'fern' }
local ignore_buftypes = { 'nofile', 'prompt', 'popup' }
local tree_width = 30

local augroup = vim.api.nvim_create_augroup('FocusDisable', { clear = true })

vim.api.nvim_create_autocmd('BufEnter', {
	group = augroup,
	callback = function(_)
		if vim.tbl_contains(ignore_buftypes, vim.bo.buftype) then
			vim.b.focus_disable = true
		end
	end,
	desc = 'Disable focus autoresize for BufType',
})


vim.api.nvim_create_autocmd('WinEnter', {
	group = augroup,
	callback = function(_)
		if vim.tbl_contains(ignore_treetypes, vim.bo.filetype) then
			vim.b.focus_disable = true
		end
	end,
	desc = 'Disable focus autoresize for BufType',
})
```

**Comment by beauwilliams** [comment]
> Note that it's the user responsibility to disable focus if he doesn't want it. Here is an example:
> 
> ```lua
>     -- Disable focus
>     local ignore_filetypes = { 'neo-tree' }
>     local ignore_buftypes = { 'nofile', 'prompt', 'popup' }
> 
>     local augroup =
>         vim.api.nvim_create_augroup('FocusDisable', { clear = true })
> 
>     vim.api.nvim_create_autocmd('WinEnter', {
>         group = augroup,
>         callback = function(_)
>             if vim.tbl_contains(ignore_buftypes, vim.bo.buftype) then
>                 vim.b.focus_disable = true
>             end
>         end,
>         desc = 'Disable focus autoresize for BufType',
>     })
> 
>     vim.api.nvim_create_autocmd('FileType', {
>         group = augroup,
>         callback = function(_)
>             if vim.tbl_contains(ignore_filetypes, vim.bo.filetype) then
>                 vim.b.focus_disable = true
>             end
>         end,
>         desc = 'Disable focus autoresize for FileType',
>     })
> ```
> 
> The readme needs to be updated with this which I haven't done yet. I tried to get rid of special handling code. Also a lot more tests need to be added.

Happy to update readme, I am also going through the changes and reviewing, looking good!

**Review by beauwilliams — APPROVED** [review]

**Review by beauwilliams — APPROVED** [review]

**Review by beauwilliams — APPROVED** [review]

**Review by beauwilliams — APPROVED** [review]

**Review by beauwilliams — APPROVED** [review]

**Comment by beauwilliams** [comment]
Thought I was clicking review per commit earlier.. But have reviewed the changes now in detail and had a play around. I'll start documenting and adding some tests as well later

**Comment by cryptomilk** [comment]
The readme should be the last one we update. I'm still trying to get rid of code while writing tests. I've also checked with diffview.nvim. You need to disable it globally not just with the buffer. Need to check DAP next.

**Comment by cryptomilk** [comment]
I've made testing a bit easier and added more tests.

**Comment by cryptomilk** [comment]
colorcolumn support didn't work at all, untested code is broken code ;-)

**Comment by cryptomilk** [comment]
Can we move to an organization with the rewrite?

**Comment by beauwilliams** [comment]
Looking good! I'll have a review over ASAP. Just coming back from short holiday

**Comment by cryptomilk** [comment]
Could we create an organization for the plugin and move the repo there? I can take over maintainer ship if you don't have time for it.

**Comment by beauwilliams** [comment]
That sounds like a great idea. It'll give the community more autonomy over the direction and easier to move to change things as needed

**Comment by cryptomilk** [comment]
I've created an org and invited you. Could you transfer the repo there? It can be done in settings. Once we have it and and merge the refactoring I can start adding CI tasks.

**Comment by cryptomilk** [comment]
You have full permissions now.

**Comment by beauwilliams** [comment]
Thanks! I am going to make some time in my week moving forward to get this all set up. I'm happy to start getting ready to merge this in.

I'll spend some time to think about community using focus if we should make announcement somewhere to let them know of the major refactor and breaking changes

Only thing for now is I want to minimise breaking changes so best way we can navigate that 👍

**Comment by cryptomilk** [comment]
There are two ways forward:

1. We create a new repo in the nvim-focus group and finish the new version. This means new bugtracker.
2. Move this repo, this mean you transfer all merge requests and issues over

The first option means people will not get all the breaking changes but might also not notice that we moved. However we could do one commit which prints a message at one point.

A friend also found a bug with the split_nicely function. I can easily reproduce it with the tests, but need to think about the bugfix.

**Comment by beauwilliams** [comment]
I will ask on r/neovim this week get some consensus 👍 

I think deploying breaking changes and doing it in a way that allows developers to update in their time is best for all. We can most likely merge as is, but just make sure to give enough heads up

**Comment by beauwilliams** [comment]
I have devised a rollout plan

1. Merge into refactor branch
2. Make Reddit PSA and show how to use new version on refactor branch with code example
3. State on announcement in X time say 1 moth we merge it to main
4. Merge to main, announce on Reddit etc 
5. Make patch to refactor branch with message saying to move to main

**Comment by cryptomilk** [comment]
Then move it to the organization first. Users will be redirected if you transfer the project.

**Comment by beauwilliams** [comment]
I think we should include a default autocommand for first time users, I'll add one this evening when I transfer to shared org

**Comment by beauwilliams** [comment]
Hey @cryptomilk I've transferred the repo! Apologies for the delay.

**Comment by cryptomilk** [comment]
I'm closing this. This is part of the refactor branch now.

**Pull request closed without merging**
